baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft4 Scaffolding Ddev'
primary: true
siteGroup: cc5695ce-fe88-4b1b-a774-d1d2d549da00 # Craft4 Scaffolding Ddev
sortOrder: 1
